## Fire Explosion - Impact VFX for fireball
## Generated by VFX Generator skill
## Type: Impact | Element: Fire
extends Node2D

# ===== CONSTANTS =====
const DURATION: float = 0.4
const SHAKE_INTENSITY: float = 12.0

# ===== COLORS =====
const BURST_COLOR = Color("#ff6b35")   # Orange
const FLASH_COLOR = Color("#ffdc00")   # Yellow
const GLOW_COLOR = Color("#ff8c42")    # Warm orange

# ===== NODE REFERENCES =====
@onready var burst: GPUParticles2D = $Burst
@onready var flash: ColorRect = $Flash
@onready var light_burst: PointLight2D = $LightBurst

# ===== LIFECYCLE =====
func _ready() -> void:
	_play_effect()

func _play_effect() -> void:
	print("[FireExplosion] Playing")

	# Camera shake
	_shake_camera()

	# Animate flash (scale up and fade)
	var tween = create_tween()
	tween.set_parallel(true)

	# Flash scales up quickly
	flash.scale = Vector2(0.5, 0.5)
	tween.tween_property(flash, "scale", Vector2(2.5, 2.5), DURATION * 0.4).set_ease(Tween.EASE_OUT)

	# Flash fades out
	tween.tween_property(flash, "modulate:a", 0.0, DURATION * 0.5)

	# Light burst fades
	tween.tween_property(light_burst, "energy", 0.0, DURATION * 0.6)

	# Ensure burst plays
	burst.emitting = true

	# Auto-destroy after effect completes
	await get_tree().create_timer(DURATION + 0.2).timeout
	queue_free()

func _shake_camera() -> void:
	var camera = get_viewport().get_camera_2d()
	if not camera:
		return

	var original_offset = camera.offset

	# Quick shake sequence
	var shake_tween = create_tween()
	for i in range(6):
		var offset = Vector2(
			randf_range(-SHAKE_INTENSITY, SHAKE_INTENSITY),
			randf_range(-SHAKE_INTENSITY, SHAKE_INTENSITY)
		)
		shake_tween.tween_property(camera, "offset", original_offset + offset, 0.05)

	# Return to original position
	shake_tween.tween_property(camera, "offset", original_offset, 0.1)
