## Frost Shatter - Ice impact VFX
## Generated by VFX Generator skill
## Type: Impact | Element: Ice
extends Node2D

# ===== CONSTANTS =====
const DURATION: float = 0.5
const SHAKE_INTENSITY: float = 8.0

# ===== COLORS =====
const SHARD_COLOR = Color("#e0f2fe")      # Pale blue/white
const MIST_COLOR = Color("#3b82f6")       # Blue mist
const FLASH_COLOR = Color("#e0f2fe")      # Bright flash
const GLOW_COLOR = Color("#60a5fa")       # Light blue glow

# ===== NODE REFERENCES =====
@onready var shards: GPUParticles2D = $Shards
@onready var mist: GPUParticles2D = $Mist
@onready var flash: Polygon2D = $Flash
@onready var light_burst: PointLight2D = $LightBurst

# ===== LIFECYCLE =====
func _ready() -> void:
	_play_effect()

func _play_effect() -> void:
	print("[FrostShatter] Playing")

	# Camera shake (lighter than fire)
	_shake_camera()

	# Animate flash - sharp crystalline burst
	var tween = create_tween()
	tween.set_parallel(true)

	# Flash scales up sharply then fades
	flash.scale = Vector2(0.3, 0.3)
	tween.tween_property(flash, "scale", Vector2(2.0, 2.0), DURATION * 0.25).set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_BACK)

	# Flash fades out
	tween.tween_property(flash, "modulate:a", 0.0, DURATION * 0.4)

	# Light burst fades
	tween.tween_property(light_burst, "energy", 0.0, DURATION * 0.5)

	# Start particles
	shards.emitting = true
	mist.emitting = true

	# Auto-destroy after effect completes
	await get_tree().create_timer(DURATION + 0.4).timeout
	queue_free()

func _shake_camera() -> void:
	var camera = get_viewport().get_camera_2d()
	if not camera:
		return

	var original_offset = camera.offset

	# Quick sharp shake for ice cracking feel
	var shake_tween = create_tween()
	for i in range(4):
		var offset = Vector2(
			randf_range(-SHAKE_INTENSITY, SHAKE_INTENSITY),
			randf_range(-SHAKE_INTENSITY, SHAKE_INTENSITY)
		)
		shake_tween.tween_property(camera, "offset", original_offset + offset, 0.04)

	# Return to original position
	shake_tween.tween_property(camera, "offset", original_offset, 0.08)
