## Fireball - Fire projectile VFX
## Generated by VFX Generator skill
## Type: Projectile | Element: Fire
extends Node2D

# ===== EXPORTED PROPERTIES =====
@export var speed: float = 450.0
@export var direction: Vector2 = Vector2.RIGHT
@export var max_distance: float = 800.0
@export var pierce_count: int = 0  # 0 = destroy on first hit
@export var impact_effect: PackedScene

# ===== COLORS =====
const CORE_COLOR = Color("#ffdc00")         # Yellow core
const MID_COLOR = Color("#ff6b35")          # Orange mid
const OUTER_COLOR = Color("#ff4136")        # Red-orange outer
const GLOW_COLOR = Color("#ff8c42")         # Warm orange glow

# ===== ANIMATION =====
const PULSE_SPEED: float = 8.0
const PULSE_AMOUNT: float = 0.15
const WOBBLE_SPEED: float = 12.0
const WOBBLE_AMOUNT: float = 0.08

# ===== INTERNAL STATE =====
var _traveled: float = 0.0
var _pierced: int = 0
var _time: float = 0.0

# ===== NODE REFERENCES =====
@onready var visual: Node2D = $Visual
@onready var outer_glow: Polygon2D = $Visual/OuterGlow
@onready var mid_glow: Polygon2D = $Visual/MidGlow
@onready var core: Polygon2D = $Visual/Core
@onready var trail: GPUParticles2D = $Trail
@onready var glow: PointLight2D = $Glow
@onready var hitbox: Area2D = $Hitbox

# ===== LIFECYCLE =====
func _ready() -> void:
	_connect_signals()
	print("[Fireball] Spawned")

func _connect_signals() -> void:
	hitbox.area_entered.connect(_on_hit)
	hitbox.body_entered.connect(_on_hit)

func _process(delta: float) -> void:
	_time += delta

	# Move forward
	var movement = direction.normalized() * speed * delta
	position += movement
	_traveled += movement.length()

	# Face direction of travel
	rotation = direction.angle()

	# Animate visual - pulsing and wobbling for organic feel
	_animate_visual()

	# Max distance check
	if _traveled >= max_distance:
		_spawn_impact()
		queue_free()

func _animate_visual() -> void:
	# Pulse scale for breathing effect
	var pulse = 1.0 + sin(_time * PULSE_SPEED) * PULSE_AMOUNT
	visual.scale = Vector2(pulse, pulse)

	# Wobble the layers independently for organic feel
	var wobble1 = sin(_time * WOBBLE_SPEED) * WOBBLE_AMOUNT
	var wobble2 = cos(_time * WOBBLE_SPEED * 1.3) * WOBBLE_AMOUNT
	outer_glow.scale = Vector2(1.0 + wobble1, 1.0 - wobble1)
	mid_glow.scale = Vector2(1.0 - wobble2, 1.0 + wobble2)

	# Flicker the glow energy
	glow.energy = 1.5 + sin(_time * PULSE_SPEED * 2.0) * 0.4

# ===== COLLISION =====
func _on_hit(body: Node2D) -> void:
	# Ignore other projectiles
	if body.is_in_group("projectile"):
		return

	_pierced += 1

	if _pierced > pierce_count:
		_spawn_impact()
		queue_free()

func _spawn_impact() -> void:
	if impact_effect:
		var impact = impact_effect.instantiate()
		get_parent().add_child(impact)
		impact.global_position = global_position
		impact.rotation = direction.angle()

# ===== PUBLIC API =====
func set_direction(dir: Vector2) -> void:
	## Set the travel direction
	direction = dir.normalized()

func set_target(target_pos: Vector2) -> void:
	## Point toward a target position
	direction = (target_pos - global_position).normalized()
