## Ice Shard - Ice projectile VFX
## Generated by VFX Generator skill
## Type: Projectile | Element: Ice
extends Node2D

# ===== EXPORTED PROPERTIES =====
@export var speed: float = 520.0
@export var direction: Vector2 = Vector2.RIGHT
@export var max_distance: float = 700.0
@export var pierce_count: int = 0
@export var impact_effect: PackedScene

# ===== COLORS =====
const CORE_COLOR = Color("#e0f2fe")       # Pale blue/white core
const MID_COLOR = Color("#06b6d4")        # Cyan mid
const OUTER_COLOR = Color("#3b82f6")      # Blue outer
const GLOW_COLOR = Color("#60a5fa")       # Light blue glow

# ===== ANIMATION CONSTANTS =====
const SHIMMER_SPEED: float = 15.0         # Crystal shimmer speed
const SHIMMER_AMOUNT: float = 0.12        # Shimmer intensity
const PULSE_SPEED: float = 6.0            # Slower pulse than fire
const PULSE_AMOUNT: float = 0.08          # Subtle pulse

# ===== INTERNAL STATE =====
var _traveled: float = 0.0
var _pierced: int = 0
var _time: float = 0.0

# ===== NODE REFERENCES =====
@onready var visual: Node2D = $Visual
@onready var outer_glow: Polygon2D = $Visual/OuterGlow
@onready var mid_layer: Polygon2D = $Visual/MidLayer
@onready var core: Polygon2D = $Visual/Core
@onready var trail: GPUParticles2D = $Trail
@onready var glow: PointLight2D = $Glow
@onready var hitbox: Area2D = $Hitbox

# ===== LIFECYCLE =====
func _ready() -> void:
	_connect_signals()
	print("[IceShard] Spawned")

func _connect_signals() -> void:
	hitbox.area_entered.connect(_on_hit)
	hitbox.body_entered.connect(_on_hit)

func _process(delta: float) -> void:
	_time += delta

	# Move forward
	var movement = direction.normalized() * speed * delta
	position += movement
	_traveled += movement.length()

	# Face direction of travel
	rotation = direction.angle()

	# Animate visual - crystalline shimmer effect
	_animate_visual()

	# Max distance check
	if _traveled >= max_distance:
		_spawn_impact()
		queue_free()

func _animate_visual() -> void:
	# Subtle pulse for icy glow
	var pulse = 1.0 + sin(_time * PULSE_SPEED) * PULSE_AMOUNT
	visual.scale = Vector2(pulse, pulse)

	# Crystal shimmer - modulate alpha slightly for sparkle effect
	var shimmer = 0.85 + sin(_time * SHIMMER_SPEED) * SHIMMER_AMOUNT
	core.modulate.a = shimmer

	# Secondary shimmer on mid layer (offset phase)
	var shimmer2 = 0.75 + cos(_time * SHIMMER_SPEED * 1.2) * SHIMMER_AMOUNT
	mid_layer.modulate.a = shimmer2

	# Glow energy fluctuation
	glow.energy = 1.0 + sin(_time * PULSE_SPEED * 1.5) * 0.25

# ===== COLLISION =====
func _on_hit(body: Node2D) -> void:
	# Ignore other projectiles
	if body.is_in_group("projectile"):
		return

	_pierced += 1

	if _pierced > pierce_count:
		_spawn_impact()
		queue_free()

func _spawn_impact() -> void:
	if impact_effect:
		var impact = impact_effect.instantiate()
		get_parent().add_child(impact)
		impact.global_position = global_position
		impact.rotation = direction.angle()

# ===== PUBLIC API =====
func set_direction(dir: Vector2) -> void:
	## Set the travel direction
	direction = dir.normalized()

func set_target(target_pos: Vector2) -> void:
	## Point toward a target position
	direction = (target_pos - global_position).normalized()
